min_range: 1
max_range: 5
assignment_rate_threshold: 0.9
cross_validation_replicates: 100
working_directory: "./"

structure_file: "snpAIMeR_toy_dataset_176inds_5SNPs.str"
number_of_individuals: 176
number_of_loci: 5
one_data_row_per_individual: FALSE
column_sample_IDs: 1
column_population_assignments: 2
column_other_info:
row_markernames: 1
no_genotype_character: -9
optional_population_info:
genotype_character_separator:
