min_range: 1
max_range: 2
assignment_rate_threshold: 0.9
cross_validation_replicates: 1000

structure_file: "SNP_check_toy_dataset_176inds_15SNPs.str"
number_of_individuals: 176
number_of_loci: 15
one_data_row_per_individual: FALSE
column_sample_IDs: 1
column_population_assignments: 2
column_other_info:
row_markernames: 1
no_genotype_character: -9
optional_population_info:
genotype_character_separator:
